// Generated by CoffeeScript 1.6.2
(function() {
  feature("Index Page", function(context, browser, $) {
    before(function(done) {
      return browser.visit('/', done);
    });
    return it("display an input and join button", function(done) {
      return wait.until($('input[ng-model="name"]').is.visible, function() {
        $({
          button: 'Join'
        }).visible.should.be["true"];
        return done();
      });
    });
  });

  feature("Register As Ray", function(context, browser, $) {
    before(function(done) {
      return browser.visit('/', done);
    });
    return it("display register's name after click Join", function(done) {
      return context.register_ready(function() {
        $("#chatters").visible.should.be["false"];
        context.register('ray');
        return wait.until($({
          link: 'ray'
        }).is.present, function() {
          $({
            button: 'Join'
          }).visible.should.be["false"];
          browser.page.render('tmp/public_msg.png');
          $("#public_msg_box").text.should.to.include('Welcome ray');
          return done();
        });
      });
    });
  });

  feature("Register As System", function(context, browser, $) {
    before(function(done) {
      return browser.visit('/', done);
    });
    return it("show error when register as System", function(done) {
      return context.register_ready(function() {
        context.register('System');
        $('#register_fail').text.should.to.include('reserved');
        return done();
      });
    });
  });

}).call(this);
