// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(socket) {
    socket.on('join', function(name) {
      socket.chaterName = name;
      chatters.push(name);
      socket.emit('chatters', chatters);
      socket.emit('notice', {
        from: 'System',
        content: "Welcome <b>" + name + "</b>"
      });
      socket.broadcast.emit('notice', {
        from: 'System',
        content: "<b>" + name + "</b> Join the chatroom"
      });
      return socket.broadcast.emit('chatters', chatters);
    });
    socket.on('disconnect', function() {
      var name;

      name = socket.chaterName;
      console.log('###disconnect ' + name);
      if (name != null) {
        global.chatters = __.without(chatters, name);
        console.log(chatters);
        socket.broadcast.emit('chatters', chatters);
        return socket.broadcast.emit('notice', {
          from: 'System',
          content: "" + name + " Leave the chatroom"
        });
      }
    });
    return socket.on('current_chatters', function() {
      return socket.emit('chatters', chatters);
    });
  };

}).call(this);
